version: '3'

services:
  app:
    depends_on:
      # - db
      - redis
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: always
    volumes:
      - .:/app
    command: bash -c "rm -f tmp/pids/server.pid && rm -f tmp/pids/sidekiq.pid && sidekiq -d -C config/sidekiq.yml && rails s -p 3000 -b 0.0.0.0"
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV="${RAILS_ENV}"
      - SECRET_KEY_BASE="${SECRET_KEY_BASE}"
      - API_KEY="${API_KEY}"
      - DATABASE_ADAPTER="${DATABASE_ADAPTER:-pg}"
      - DATABASE_HOST="${DATABASE_HOST}"
      - DATABASE_USERNAME="${DATABASE_USERNAME}"
      - DATABASE_PASSWORD="${DATABASE_PASSWORD}"
      - S3_ACCESS_KEY_ID="${S3_ACCESS_KEY_ID}"
      - S3_SECRET_ACCESS_KEY="${S3_SECRET_ACCESS_KEY}"
      - S3_REGION="${S3_REGION}"
      - S3_BUCKET="${S3_BUCKET}"
      - RECAPTCHA_PUBLIC_KEY="${RECAPTCHA_PUBLIC_KEY}"
      - RECAPTCHA_PRIVATE_KEY="${RECAPTCHA_PRIVATE_KEY}"
      - SIDEKIQ_PASSWORD="${SIDEKIQ_PASSWORD}"
      - CONTAS_RSA="${CONTAS_RSA}"
      - CONTAS_RSA_PUB="${CONTAS_RSA_PUB}"
      - MAILER_USERNAME="${MAILER_USERNAME}"
      - MAILER_API_KEY="${MAILER_API_KEY}"
      - MAILER_PASSWORD="${MAILER_PASSWORD}"
      - MAILER_SMTP_ADDRESS="${MAILER_SMTP_ADDRESS}"
      - MAILER_SMTP_PORT="${MAILER_SMTP_PORT}"
      
  # db:
  #   image: postgres
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis:4.0-alpine
    command: redis-server
    volumes:
      - ./tmp/db:/data
